In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("Bengaluru_House_Data.csv")

In [ ]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
df.shape

(13320, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(529)

In [ ]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [ ]:
df[df.duplicated()].head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
971,Super built-up Area,Ready To Move,Haralur Road,3 BHK,NRowse,1464,3.0,2.0,56.0
1115,Super built-up Area,Ready To Move,Haralur Road,2 BHK,NaN,1027,2.0,2.0,44.0
1143,Super built-up Area,Ready To Move,Vittasandra,2 BHK,Prlla C,1246,2.0,1.0,64.5
1290,Super built-up Area,Ready To Move,Haralur Road,2 BHK,NaN,1194,2.0,2.0,47.0
1394,Super built-up Area,Ready To Move,Haralur Road,2 BHK,NaN,1027,2.0,2.0,44.0

In [ ]:
df[df.duplicated()].shape

(529, 9)

df[df.duplicated()].head()

In [ ]:
df["size"].value_counts().head(20)

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
Name: count, dtype: int64

In [ ]:
df["bath"].value_counts().sort_index()

bath
1.0      788
2.0     6908
3.0     3286
4.0     1226
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
11.0       3
12.0       7
13.0       3
14.0       1
15.0       1
16.0       2
18.0       1
27.0       1
40.0       1
Name: count, dtype: int64

In [ ]:
df["balcony"].value_counts().sort_index()

balcony
0.0    1029
1.0    4897
2.0    5113
3.0    1672
Name: count, dtype: int64

In [ ]:
df["total_sqft"].unique()[:30]

array(['1056', '2600', '1440', '1521', '1200', '1170', '2732', '3300',
       '1310', '1020', '1800', '2785', '1000', '1100', '2250', '1175',
       '1180', '1540', '2770', '600', '1755', '2800', '1767', '510',
       '1250', '660', '1610', '1151', '1025', '2100 - 2850'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean = df_clean.drop("society", axis=1)

In [ ]:
df_clean.columns

Index(['area_type', 'availability', 'location', 'size', 'total_sqft', 'bath',
       'balcony', 'price'],
      dtype='object')

In [ ]:
df_clean = df_clean.drop_duplicates()
df_clean.shape

(12752, 8)

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
df_clean = df_clean.dropna(subset=["location", "size"])
df_clean.isnull().sum()

area_type         0
availability      0
location          0
size              0
total_sqft        0
bath             57
balcony         589
price             0
dtype: int64

In [ ]:
df_clean["bhk"] = df_clean["size"].str.extract(r"(\d+)").astype(float)
df_clean[["size", "bhk"]].head(20)

         size  bhk
0       2 BHK  2.0
1   4 Bedroom  4.0
2       3 BHK  3.0
3       3 BHK  3.0
4       2 BHK  2.0
5       2 BHK  2.0
6       4 BHK  4.0
7       4 BHK  4.0
8       3 BHK  3.0
9   6 Bedroom  6.0
10      3 BHK  3.0
11  4 Bedroom  4.0
12      2 BHK  2.0
13      2 BHK  2.0
14  3 Bedroom  3.0
15      2 BHK  2.0
16      3 BHK  3.0
17      3 BHK  3.0
18      3 BHK  3.0
19      2 BHK  2.0

In [ ]:
pd.to_numeric(df_clean["total_sqft"], errors="coerce").isna().sum()

np.int64(238)

In [ ]:
df_clean.loc[
    pd.to_numeric(df_clean["total_sqft"], errors="coerce").isna(),
    "total_sqft"
].unique()
df_clean[["size", "bhk"]].head(20)

         size  bhk
0       2 BHK  2.0
1   4 Bedroom  4.0
2       3 BHK  3.0
3       3 BHK  3.0
4       2 BHK  2.0
5       2 BHK  2.0
6       4 BHK  4.0
7       4 BHK  4.0
8       3 BHK  3.0
9   6 Bedroom  6.0
10      3 BHK  3.0
11  4 Bedroom  4.0
12      2 BHK  2.0
13      2 BHK  2.0
14  3 Bedroom  3.0
15      2 BHK  2.0
16      3 BHK  3.0
17      3 BHK  3.0
18      3 BHK  3.0
19      2 BHK  2.0